version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "MiPass123!"
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql

  examen1-ui:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "5000:80"
    depends_on:
      - sqlserver
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=Examen1;User Id=sa;Password=TuPasswordSegura;

volumes:
  sqlserverdata:

